# Site settings
title: Connectivity Atlas | Development Seed
baseurl: "/mapping-future" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown

collections:
  sources:
    output: true
    permalink: /source/:path/
    layout: source
  themes:
    output: true
    permalink: /:path/
    layout: theme
