_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -96.6797
  - 38.3417
  - 3
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 6
minzoom: 0
name: ''
source: "tmsource:///Users/dan/Documents/mapping-future/layers/pipeplines-oil.tm2source"
styles: 
  - style.mss
template: ''
